export const tipoBecaOptions = [
    { value: 'Doctorado', label: 'Doctorado' },
    { value: 'Maestría', label: 'Maestría' },
    { value: 'Grado', label: 'Grado' },
    { value: 'Posgrado', label: 'Posgrado' },
    { value: 'Fondos para investigación', label: 'Fondos para investigación' },
    { value: 'Estancia de investigación', label: 'Estancia de investigación' },
    { value: 'Posdoctorado', label: 'Posdoctorado' },
]

export const nivelAcademicoOptions = [
    { value: 'Doctorado', label: 'Doctorado' },
    { value: 'Maestría', label: 'Maestría' },
    { value: 'Grado', label: 'Grado' },
    { value: 'Posgrado', label: 'Posgrado' },
    { value: 'Posdoctorado', label: 'Posdoctorado' },
]

export const regionOptions = [
    { value: 'África', label: 'África' },
    { value: 'América del Norte', label: 'América del Norte' },
    { value: 'América Latina', label: 'América Latina' },
    { value: 'Asia', label: 'Asia' },
    { value: 'Centroamérica', label: 'Centroamérica' },
    { value: 'Europa', label: 'Europa' },
    { value: 'Oceanía', label: 'Oceanía' },
].sort((a, b) => a.label.localeCompare(b.label))

export const countryOptions = [
    // América Latina
    { value: 'Argentina', label: 'Argentina' },
    { value: 'Bolivia', label: 'Bolivia' },
    { value: 'Brasil', label: 'Brasil' },
    { value: 'Chile', label: 'Chile' },
    { value: 'Colombia', label: 'Colombia' },
    { value: 'Cuba', label: 'Cuba' },
    { value: 'República Dominicana', label: 'República Dominicana' },
    { value: 'Ecuador', label: 'Ecuador' },
    { value: 'México', label: 'México' },
    { value: 'Paraguay', label: 'Paraguay' },
    { value: 'Perú', label: 'Perú' },
    { value: 'Uruguay', label: 'Uruguay' },
    { value: 'Venezuela', label: 'Venezuela' },
    // Centroamérica
    { value: 'Costa Rica', label: 'Costa Rica' },
    { value: 'El Salvador', label: 'El Salvador' },
    { value: 'Guatemala', label: 'Guatemala' },
    { value: 'Honduras', label: 'Honduras' },
    { value: 'Nicaragua', label: 'Nicaragua' },
    { value: 'Panamá', label: 'Panamá' },
    { value: 'Belice', label: 'Belice' },
    // América del Norte
    { value: 'Canadá', label: 'Canadá' },
    { value: 'Estados Unidos', label: 'Estados Unidos' },
    // Europa
    { value: 'Albania', label: 'Albania' },
    { value: 'Andorra', label: 'Andorra' },
    { value: 'Armenia', label: 'Armenia' },
    { value: 'Austria', label: 'Austria' },
    { value: 'Azerbaiyán', label: 'Azerbaiyán' },
    { value: 'Bielorrusia', label: 'Bielorrusia' },
    { value: 'Bélgica', label: 'Bélgica' },
    { value: 'Bosnia y Herzegovina', label: 'Bosnia y Herzegovina' },
    { value: 'Bulgaria', label: 'Bulgaria' },
    { value: 'Croacia', label: 'Croacia' },
    { value: 'Chipre', label: 'Chipre' },
    { value: 'República Checa', label: 'República Checa' },
    { value: 'Dinamarca', label: 'Dinamarca' },
    { value: 'Estonia', label: 'Estonia' },
    { value: 'Finlandia', label: 'Finlandia' },
    { value: 'Francia', label: 'Francia' },
    { value: 'Georgia', label: 'Georgia' },
    { value: 'Alemania', label: 'Alemania' },
    { value: 'Grecia', label: 'Grecia' },
    { value: 'Hungría', label: 'Hungría' },
    { value: 'Islandia', label: 'Islandia' },
    { value: 'Irlanda', label: 'Irlanda' },
    { value: 'Italia', label: 'Italia' },
    { value: 'Kazajistán', label: 'Kazajistán' },
    { value: 'Kosovo', label: 'Kosovo' },
    { value: 'Letonia', label: 'Letonia' },
    { value: 'Liechtenstein', label: 'Liechtenstein' },
    { value: 'Lituania', label: 'Lituania' },
    { value: 'Luxemburgo', label: 'Luxemburgo' },
    { value: 'Malta', label: 'Malta' },
    { value: 'Moldavia', label: 'Moldavia' },
    { value: 'Mónaco', label: 'Mónaco' },
    { value: 'Montenegro', label: 'Montenegro' },
    { value: 'Países Bajos', label: 'Países Bajos' },
    { value: 'Macedonia del Norte', label: 'Macedonia del Norte' },
    { value: 'Noruega', label: 'Noruega' },
    { value: 'Polonia', label: 'Polonia' },
    { value: 'Portugal', label: 'Portugal' },
    { value: 'Rumania', label: 'Rumania' },
    { value: 'Rusia', label: 'Rusia' },
    { value: 'San Marino', label: 'San Marino' },
    { value: 'Serbia', label: 'Serbia' },
    { value: 'Eslovaquia', label: 'Eslovaquia' },
    { value: 'Eslovenia', label: 'Eslovenia' },
    { value: 'España', label: 'España' },
    { value: 'Suecia', label: 'Suecia' },
    { value: 'Suiza', label: 'Suiza' },
    { value: 'Turquía', label: 'Turquía' },
    { value: 'Ucrania', label: 'Ucrania' },
    { value: 'Reino Unido', label: 'Reino Unido' },
    { value: 'Ciudad del Vaticano', label: 'Ciudad del Vaticano' },
].sort((a, b) => a.label.localeCompare(b.label, 'es', { sensitivity: 'base' }))

export const duracionUnidadOptions = [
    { value: 'años', label: 'Años' },
    { value: 'meses', label: 'Meses' },
    { value: 'semanas', label: 'Semanas' },
].sort((a, b) => a.label.localeCompare(b.label))

export const idiomaOptions = [
    { value: 'Español', label: 'Español' },
    { value: 'Chino Mandarín', label: 'Chino Mandarín' },
    { value: 'Inglés', label: 'Inglés' },
    { value: 'Hindi', label: 'Hindi' },
    { value: 'Bengalí', label: 'Bengalí' },
    { value: 'Portugués', label: 'Portugués' },
    { value: 'Ruso', label: 'Ruso' },
    { value: 'Japonés', label: 'Japonés' },
    { value: 'Alemán', label: 'Alemán' },
    { value: 'Francés', label: 'Francés' },
    { value: 'Italiano', label: 'Italiano' },
    { value: 'Turco', label: 'Turco' },
    { value: 'Árabe', label: 'Árabe' },
    { value: 'Urdu', label: 'Urdu' },
    { value: 'Panyabí', label: 'Panyabí' },
    { value: 'Neerlandés', label: 'Neerlandés' },
    { value: 'Coreano', label: 'Coreano' },
    { value: 'Vietnamita', label: 'Vietnamita' },
    { value: 'Tamil', label: 'Tamil' },
    { value: 'Persa', label: 'Persa (Farsi)' },
].sort((a, b) => a.label.localeCompare(b.label, 'es'))

export const nivelIdiomaOptions = [
    { value: 'A1', label: 'A1 (Principiante)' },
    { value: 'A2', label: 'A2 (Elemental)' },
    { value: 'B1', label: 'B1 (Intermedio)' },
    { value: 'B2', label: 'B2 (Intermedio Alto)' },
    { value: 'C1', label: 'C1 (Avanzado)' },
    { value: 'C2', label: 'C2 (Casi Nativo)' },
]
